name: e2e
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      matrix:
        os:
        - macos-14
        - ubuntu-22.04
        - windows-2022
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Get Node version from Node manifest
        run: echo "NODE_VER=$(curl -s https://nwjs.io/versions.json | jq -r ".versions[0].components.node")" >> $GITHUB_ENV
      - name: Setup Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ${{ env.NODE_VER }}
          cache: "npm"
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: npm ci
      - name: Link module
        run: npm link grunt-nw-builder
      - name: Run tests
        run: npm run test
