name: rel

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-22.04
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4.1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
